---
title: "DGE"
author: "viv3kanand"
date: "2023-05-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Required packages
```{r, include=FALSE, warning=FALSE, message=FALSE}
require(DESeq2)
require(tidyverse)
BiocParallel::register(BiocParallel::MulticoreParam(40))
```

### Load DGE data from tximport
```{r}
source("../scripts/tximport.R")

dir = "../data/salmon"

samples <- read.csv("../data/metadata.csv", header = TRUE)

gse <- tximport(dir=dir, coldata=samples, txdf="../data/txdf.csv", DTE=FALSE)

saveRDS(gse,"RData/gse.rds")
```

### DGE
```{r}
gse <- readRDS("RData/gse.rds")

gse_list <- list("iPSC" = gse[,gse$Cell_line == "iPSC"],
              "NSC" = gse[,gse$Cell_line == "NSC"],
              "NEU" = gse[,gse$Cell_line == "Neuron"])


lapply(gse_list, function(se){
  
  if (length(unique(colData(se)$Batch)) > 1 & length(unique(colData(se)$Sex)) > 1) {
    se$Condition <- relevel(se$Condition, ref = "Control")
    dds <- DESeqDataSetFromMatrix(countData = round(assays(se)[["counts"]]),
                              colData = colData(se),
                              design = ~ Batch + Sex + Condition)
  }
  else if (length(unique(colData(se)$Batch)) > 1 & length(unique(colData(se)$Sex)) < 1) {
    se$Condition <- relevel(se$Condition, ref = "Control")
    dds <- DESeqDataSetFromMatrix(countData = round(assays(se)[["counts"]]),
                              colData = colData(se),
                              design = ~ Batch + Condition)
  }
  else if (length(unique(colData(se)$Batch)) < 1 & length(unique(colData(se)$Sex)) > 1) {
    se$Condition <- relevel(se$Condition, ref = "Control")
    dds <- DESeqDataSetFromMatrix(countData = round(assays(se)[["counts"]]),
                              colData = colData(se),
                              design = ~ Sex + Condition)
  }
  else {
    se$Condition <- relevel(se$Condition, ref = "Control")
    dds <- DESeqDataSetFromMatrix(countData = round(assays(se)[["counts"]]),
                              colData = colData(se),
                              design = ~ Condition)
  }
  
  keep <- rowSums(counts(dds) >= 5) >= 3
  table(keep)
  dds <- dds[keep,]
  
  
  suppressWarnings(dds <- DESeq(dds, 
                                parallel = TRUE, 
                                BPPARAM=BiocParallel::MulticoreParam(40)))
  
  if (length(unique(colData(se)$Batch)) > 1) {
    vst <- vst(dds, blind=FALSE)
    mat <- assay(vst)
    mm <- model.matrix(~ Sex + Condition, colData(se))
    mat <- limma::removeBatchEffect(mat, batch=vst$Batch, design=mm) %>% as.data.frame
  }
  else {
    vst <- vst(dds, blind=FALSE)
    mat <- assay(vst)
  }
  
  res <- lfcShrink(dds, 
                   coef = "Condition_Diseased_vs_Control", 
                   type = "apeglm", parallel = TRUE, 
                   BPPARAM=BiocParallel::MulticoreParam(40)) %>% 
    as.data.frame() %>%
    tibble::rownames_to_column("ID")
  
  output = list("res" = res, "dds" = dds, "vst" = mat)
  return(output)
  
}) -> gse_out

saveRDS(gse_out, file = "RData/gse_out.rds")
```


### Create vst for Visualization
```{r}
dds <- DESeqDataSetFromMatrix(countData = round(assays(gse)[["counts"]]),
                              colData = colData(gse),
                              design = ~ Batch + Sex + Condition)

keep <- rowSums(counts(dds) >= 5) >= 3
table(keep)
dds <- dds[keep,]

suppressWarnings(dds <- DESeq(dds, parallel = TRUE, BPPARAM = BiocParallel::MulticoreParam(40)))

vst <- vst(dds, blind=FALSE)
mat <- assay(vst)
mm <- model.matrix(~ Sex + Condition, colData(gse))
mat <- limma::removeBatchEffect(mat, batch=vst$Batch, design=mm) %>% as.data.frame

saveRDS(mat, "RData/vst_bc.rds")
```
















