---
title: "Figures"
author: "viv3kanand"
date: "2023-05-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Load packages
```{r}
require(ggplot2)
require(ggrepel)
require(ggplotify)
require(cowplot)
require(tidyverse)
require(paletteer)
require(broom)
require(circlize)
```

### Load datasets
```{r}
source("../scripts/helper_scripts.R")

se <- readRDS("RData/se.rds")
gse <- readRDS("RData/gse.rds")
se_out <- readRDS("RData/se_out.rds")
gse_out <- readRDS("RData/gse_out.rds")
dds <- readRDS("RData/dds.rds")
vst_mat <- readRDS("RData/vst_bc.rds")
dti <- readRDS("RData/dti.rds")
```

### Custom theme to apply
```{r}
# Theme elements
font <- "Helvetica"
text_size <- 10
line_size <- 0.5

# Figure elements
res <- 300
full_width <- 10
full_height <- 13
meas_units <- "in"
output_filetype <- "png"
fig_lab_size <- 9
fig_lab_pos_x <- 0
fig_lab_pos_y <- 1
label_type <- "AUTO"

custom_theme <- function(){
  theme_classic() +
    theme(text = element_text(family = font,
                              size = text_size),
          line = element_line(linewidth = line_size),
          axis.title = element_text(size = rel(1.25)),
          axis.text = element_text(size = rel(1.15)),
          plot.title = element_text(size = rel(1.5),
                                    hjust = 0.5),
          panel.grid = element_blank(),
          plot.background = element_rect(fill = "white"),
          legend.position = "right",
          legend.text=element_text(size=text_size))
}




palette1 <- c("#E64B35FF", "#417839FF")
palette2 <- c("#FF3D7FFF", "#3FB8AFFF")
palette3 <- c("#3A488AFF", "#BE3428FF") # paletteer_d("lisa::OskarSchlemmer")
palette4 <- c("#CF597EFF", "#009392FF") # paletteer_d("rcartocolor::Temps")
palette5 <- c("#CF597EFF", "#D6D6D6FF", "#009392FF")

```


### PCA of Batch effect corrected and uncorrected samples
```{r}
li <- list("Uncorrected" = dds, "Corrected" = vst_mat)

coldata <- colData(dds) %>% as.data.frame()


plot_list <- list()

# PCA plot
plot_list[["pca"]] <- purrr::imap(li, function(obj, name) {
  pca_result <- call_PCA(obj)
  p <- pca_result$pca %>% 
    augment(coldata) %>%
    mutate(Batch_Cell_line = interaction(Cell_line, Batch, sep="_")) %>% 
    ggplot(aes(x=.fittedPC1, y=.fittedPC2, color=Condition, shape = Batch_Cell_line)) + 
    geom_point(size = 3) + 
    #geom_text(aes(label = Batch), hjust=0, vjust=0) +
    ggtitle(name) +
    xlab(paste0("PC1: ",round(pca_result$percentVar[1] * 100),"% variance")) +
    ylab(paste0("PC2: ",round(pca_result$percentVar[2] * 100),"% variance")) +
    coord_fixed() +
    labs(shape="Cell line and Batch", colour="Condition") +
    scale_shape_manual(values = c(15,16,17,1,2)) +
    scale_color_manual(name = "Condition", values = palette4) +
    custom_theme()

  return(p)
})

row1 <- cowplot::plot_grid(plot_list$pca$Uncorrected + theme(legend.position="none"), 
                           plot_list$pca$Corrected + theme(legend.position="none"),
                           align = "hv")

legend1 <- get_legend(
  plot_list$pca$Uncorrected + theme(legend.box.margin = margin(0, 0, 0, 12))
)

plot_pca <- plot_grid(row1, legend1, rel_widths = c(2, .4))

```


### PCA in base R
```{r}
pca <- call_PCA(dds)
    
df <- pca$pca %>% 
  augment(coldata) %>% 
  mutate(Batch_Cell_line = factor(interaction(Cell_line, Batch, sep="_")))

# Create a color factor based on the Condition variable
df$color <- as.numeric(as.factor(df$Condition))

# Create separate point type factors based on the Batch and Cell_line variables
df$pch_batch <- as.numeric(as.factor(df$Batch))
df$pch_cell_line <- as.numeric(as.factor(df$Cell_line))
df$pch_Batch_Cell_line <- as.numeric(as.factor(df$Batch_Cell_line))

# Create a color palette and point shape vectors based on the above factors
colors <- palette4[df$color]
shapes <- c(15,16,17,1,2)[df$pch_Batch_Cell_line]

shapes_batch <- c(1,16)[df$pch_batch]
shapes_cell_line <- c(15,16,17)[df$pch_cell_line]

# Create the base plot
plot(df$.fittedPC1, df$.fittedPC2, pch=shapes, col=colors, 
     xlab=paste0("PC1: ", round(pca$percentVar[1] * 100), "% variance"), 
     ylab=paste0("PC2: ", round(pca$percentVar[2] * 100), "% variance"), 
     main="Title", bty="n")

# Create the legend
legend("topright", legend=levels(df$Condition), fill=palette4, title="Condition")
legend("bottomright", legend=levels(df$Batch), pch=c(1,16), title="Batch")
legend("bottomright", legend=levels(df$Cell_line), pch=c(15,16,17), title="Cell line")

```



### Scree plot
```{r}
plot_list[["scree"]] <- purrr::imap(li, function(obj, name) {
  pca_result <- call_PCA(obj)
  p <- data.frame(Components = paste0("PC",seq_len(5)), 
           value = pca_result$percentVar[1:5]) %>%
    ggplot(aes(x = Components, y = value)) + 
    geom_col(fill = "#009392FF", width = 0.5) + 
    ggtitle(name) +
    ylab("% of total variance") + 
    scale_y_continuous(labels = scales::percent_format(),
                       expand = expansion(mult = c(0, 0.01))) +
    custom_theme()
  
  return(p)
})
```

### PCA Loadings
```{r}
data.frame(pca$pca$x) %>% tibble::rownames_to_column("ID") %>%
    select(c(1:5)) %>% 
    pivot_longer(cols = PC1:PC4) %>% 
    mutate(ID = tidytext::reorder_within(ID, 
                                         abs(value), 
                                         name)) %>%
    ggplot(aes(abs(value), ID, fill = value > 0)) +
    geom_col() +
    facet_wrap(~name, scales = "free_y") +
    tidytext::scale_y_reordered() +
    scale_fill_manual(values = c("#009392FF", "#CF597EFF")) +
    labs(x = "Absolute value of contribution",
         y = NULL, fill = "Positive?"
    ) +
  theme_minimal()
```

### Heatmap
```{r}
plot_list[["heatmap"]] <- purrr::imap(gse_out, function(obj, name) {
  # Subset samples for plotting
  gene_list <- obj[["res"]] %>% 
    filter(abs(log2FoldChange) > 2 & padj < 0.01) %>% 
    pull("ID")
  
  mat <- obj[["vst"]][rownames(obj[["vst"]]) %in% gene_list,]
  
  meta <- colData(obj$dds) %>% as.data.frame() %>% select(Condition)
  
  # Plot functions
  # color_mapping <- colorRampPalette(c("#009392FF", "#CF597EFF"))(length(unique(meta$Condition)))
  # names(color_mapping) <- unique(meta$Condition)
  # 
  # ha = HeatmapAnnotation(
  #   Condition = anno_block(gp = gpar(fill = c("#009392FF", "#CF597EFF")),
  #   labels = c("Control", "Patient"),
  #   labels_gp = gpar(col = "white", fontsize = 10))
  # )
  
  ha <- HeatmapAnnotation(df = meta, 
                          col = list(
                            Condition = c("Control" = "#009392FF", "Diseased" = "#CF597EFF")),
                          annotation_name_side = "left",
                          show_legend = FALSE)
  
  #col_fun = paletteer_d("rcartocolor::Temps")
  col_fun = colorRamp2(c(-2, 0, 2), c("#009392FF", "#E9E29CFF", "#CF597EFF"))
  
  
  # Plot heatmap
  h <- as.ggplot(Heatmap(t(scale(t(mat))), 
                         top_annotation = ha,
                         col = col_fun,
                         column_title = name,
                         column_km = 2,
                         row_km = 2, 
                         show_row_names = FALSE,
                         show_column_names = FALSE,
                         width = unit(5, "cm"),
                         rect_gp = gpar(col = "white", lwd = 0.1),
                         name = "Scaled\nnormalized\nexpression"))
  
  return(h)
  })

#Legends
lgd1 <- Legend(col_fun = col_fun, title = "Scaled\nnormalized\nexpression")

lgd2 <- Legend(labels = c("Control", "Patient"), 
               legend_gp = gpar(fill = palette4), 
               title = "Condition")

pd = packLegend(lgd1, lgd2)

draw(ht_list, merge_legend = TRUE)

plot_heatmap <- cowplot::plot_grid(plot_list$heatmap$iPSC,
                                   plot_list$heatmap$NSC,
                                   plot_list$heatmap$Neuron,
                                   pd,
                                   align = "hv",
                                   nrow = 1,
                                   rel_widths = c(3, .4))

```


### Volcano plot
```{r}
plot_list[["volcano"]] <- purrr::imap(gse_out, function(obj, name) {
  obj[["res"]] %>%
    mutate(Expression = case_when(
      log2FoldChange >= 2 & padj <= 0.01 ~ "Upregulated",
      log2FoldChange <= -2 & padj <= 0.01 ~ "Downregulated",
      TRUE ~ "Not significant")) %>% 
    ggplot(aes(x = log2FoldChange, y = -log10(padj))) +
    geom_point(aes(color = Expression)) +
    ggtitle(name) +
    ggrepel::geom_text_repel(data = head(obj[["res"]][order(obj[["res"]][["padj"]]),], 10),
                              aes(label = ID)) +
    scale_color_manual(values = palette5) +
    scale_x_continuous(name = "Log2 fold change") +
    scale_y_continuous(name = "-Log10 padj") +
    geom_hline(yintercept = 2, linetype = 2, color = "black") +
    geom_vline(xintercept = c(-2, 2), linetype = 2, color = "black") +
    custom_theme()
})

row2 <- cowplot::plot_grid(plot_list$volcano$iPSC + theme(legend.position="none"), 
                           plot_list$volcano$NSC + theme(legend.position="none"),
                           plot_list$volcano$Neuron + theme(legend.position="none"),
                           align = "hv", nrow = 1)

legend2 <- get_legend(
  plot_list$volcano$iPSC + theme(legend.box.margin = margin(0, 0, 0, 12))
)

plot_volcano <- plot_grid(row2, legend2, rel_widths = c(3, .4))
```


```{r}
dti_norm_ct <- assay(dti, "meanScaled") %>% 
  as.data.frame() %>% 
  cbind(., symbol = mcols(dti)[match(rownames(.), rownames(mcols(dti))), "gene_name"]) %>% 
  mutate(symbol = str_replace(symbol, "gene-", ""))

ppp2r2b <- dti_norm_ct[dti_norm_ct$symbol == "PPP2R2B",] %>% 
  select(-c(24))



meta <- colData(dti) %>% as.data.frame() %>% select(Condition, Cell_line)
meta$Cell_line <- factor(meta$Cell_line, levels = c("Neuron", "NSC", "iPSC"))
meta <- meta[order(meta$Cell_line, meta$Condition),]

ha <- HeatmapAnnotation(df = meta, 
                          col = list(
                            Cell_line = c("iPSC" = "#009392FF", "NSC" = "#EEB479FF", "Neuron" = "#CF597EFF"),
                            Condition = c("Control" = "#8785B2FF", "Diseased" = "#D95F30FF")),
                        show_legend = TRUE)
  
#col_fun = paletteer_d("rcartocolor::Temps")

col_fun = colorRamp2(c(-2, 0, 2), c("#009392FF", "white", "#CF597EFF"))


Heatmap(t(scale(t(ppp2r2b[,rownames(meta)]))), 
        top_annotation = ha,
        col = col_fun,
        column_title = "PPP2R2B",
        show_row_names = TRUE,
        show_column_names = TRUE,
        cluster_columns = FALSE,
        rect_gp = gpar(col = "white", lwd = 0.1),
        name = "meanScaled\nnormalized\nexpression")
```

### Save figures
```{r}
ggsave(plot = plot_pca,
       filename = "plots/PCA.png",
       bg = "white",
       width = 10,
       height = full_height/2.5,
       units = meas_units,
       dpi = res)

ggsave(plot = plot_heatmap,
       filename = "plots/Heatmap.png",
       bg = "white",
       width = 15,
       height = full_height/1.5,
       units = meas_units,
       dpi = res)

ggsave(plot = plot_volcano,
       filename = "plots/Volcano.png",
       bg = "white",
       width = 12,
       height = full_height/2.5,
       units = meas_units,
       dpi = res)
```











